// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "b1ef30cd-52ed-45b7-a39a-6e1bbed4dbb2");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1536560012);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1536560132);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1536584852);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1536581492);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1536581372);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1536560372);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1536560252);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 880640);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1536559622);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 69);
user_pref("browser.newtabpage.activity-stream.asrouterOnboardingCohort", 1);
user_pref("browser.newtabpage.activity-stream.impressionId", "{b046f745-3a23-492a-aff8-2449e1fddbb2}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1536537600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.finished", true);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1536559623);
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots\",\"taarexpv3_shield_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"taarexpv3_shield_mozilla_org\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1536586691987");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1536588468987");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1536584830568");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1536588430568");
user_pref("browser.search.countryCode", "IN");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1536559623");
user_pref("browser.slowStartup.averageTime", 1225);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20180905221508");
user_pref("browser.startup.homepage_override.mstone", "62.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1536559624820");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "62.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "5bad63b8f92943bfad0c12ea1b34cf95");
user_pref("extensions.blocklist.lastModified", "Wed, 05 Sep 2018 22:34:28 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1536560013);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "62.0");
user_pref("extensions.lastPlatformVersion", "62.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shield-search-nudges.clicked-awesomebar", false);
user_pref("extensions.shield-search-nudges.installed_at", 1536581496);
user_pref("extensions.shield-search-nudges.oked", false);
user_pref("extensions.shield-search-nudges.shown_count", 0);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.taarexpv3_shield_mozilla_org.client-status", "{\"discoPaneLoaded\":false,\"clickedButton\":false,\"sawPopup\":false,\"startTime\":\"1536581497927\",\"totalWebNav\":0,\"aboutAddonsActiveTabSeconds\":0}");
user_pref("extensions.taarexpv3_shield_mozilla_org.originalAboutAddonsDomain", "https://discovery.addons.mozilla.org/%LOCALE%/firefox/discovery/pane/%VERSION%/%OS%/%COMPATIBILITY_MODE%");
user_pref("extensions.webextensions.uuids", "{\"webcompat@mozilla.org\":\"e1cf1b58-63fd-4766-9e90-d535c7e292ae\",\"screenshots@mozilla.org\":\"5ae53e2f-0b4c-4e21-bdcb-dc95cf4b496f\",\"taarexpv3@shield.mozilla.org\":\"a4b7213a-6abb-4ce4-9f8c-3a05add5eed3\"}");
user_pref("extensions.webservice.discoverURL", "https://discovery.addons.mozilla.org/%LOCALE%/firefox/discovery/pane/%VERSION%/%OS%/%COMPATIBILITY_MODE%?study=taarexpv3&branch=intervention-a&clientId=a81d4d3b-b0a9-472b-ae10-288961eb365c");
user_pref("idle.lastDailyNotification", 1536560506);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1536559658);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20180905221508");
user_pref("media.gmp-manager.lastCheck", 1536559657);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1536560506);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "eaad200f-f968-481f-bcf4-9608aa7f0ce5");
user_pref("services.blocklist.addons.checked", 1536522227);
user_pref("services.blocklist.gfx.checked", 1536522227);
user_pref("services.blocklist.onecrl.checked", 1536522227);
user_pref("services.blocklist.pinning.checked", 1536522227);
user_pref("services.blocklist.plugins.checked", 1536522227);
user_pref("services.settings.clock_skew_seconds", 37905);
user_pref("services.settings.last_etag", "\"1536271781916\"");
user_pref("services.settings.last_update_seconds", 1536522227);
user_pref("shield.taarexpv3_shield_mozilla_org.firstRunTimestamp", "1536581497907");
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1536560506);
user_pref("toolkit.startup.last_success", 1536559621);
user_pref("toolkit.telemetry.cachedClientID", "a81d4d3b-b0a9-472b-ae10-288961eb365c");
user_pref("toolkit.telemetry.previousBuildID", "20180905221508");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
